# Generated by Django 5.2.7 on 2025-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notecategory_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('archive', 'В архиве'), ('public', 'Опубилковано')], default='public', max_length=255),
        ),
    ]
