# Generated by Django 4.2.25 on 2025-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='картинка'),
        ),
    ]
